# Generated by Django 5.0.6 on 2024-06-02 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Judge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('specialization', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('case_type', models.CharField(max_length=100)),
                ('estimated_closure_time', models.IntegerField()),
                ('assigned_judge', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.judge')),
            ],
        ),
    ]
