# Generated by Django 5.0.6 on 2024-06-02 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='case',
            old_name='case_type',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='case',
            old_name='assigned_judge',
            new_name='judge',
        ),
        migrations.RenameField(
            model_name='judge',
            old_name='specialization',
            new_name='specialty',
        ),
        migrations.RemoveField(
            model_name='case',
            name='estimated_closure_time',
        ),
        migrations.AddField(
            model_name='case',
            name='estimated_time_to_close',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='case',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
