# Generated by Django 5.0.6 on 2024-06-04 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_judge_specialty_judge_becomes_cji_on_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='judge',
            name='becomes_cji_on',
        ),
        migrations.RemoveField(
            model_name='judge',
            name='date_of_appointment',
        ),
        migrations.RemoveField(
            model_name='judge',
            name='date_of_retirement',
        ),
        migrations.RemoveField(
            model_name='judge',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='judge',
            name='parent_high_court',
        ),
        migrations.RemoveField(
            model_name='judge',
            name='tenure_length',
        ),
        migrations.RemoveField(
            model_name='judge',
            name='tenure_length_as_cji',
        ),
        migrations.AlterField(
            model_name='case',
            name='category',
            field=models.CharField(choices=[('CR', 'Criminal'), ('CV', 'Civil'), ('FA', 'Family'), ('PR', 'Property'), ('LA', 'Labor'), ('IN', 'Intellectual Property')], max_length=2),
        ),
        migrations.AlterField(
            model_name='case',
            name='estimated_time_to_close',
            field=models.DurationField(),
        ),
        migrations.AlterField(
            model_name='case',
            name='judge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.judge'),
        ),
        migrations.AlterField(
            model_name='case',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='judge',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
