# Generated by Django 5.0.6 on 2024-06-04 13:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_judge_becomes_cji_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='judge',
            name='becomes_cji_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='judge',
            name='date_of_appointment',
            field=models.DateField(default=datetime.date(2000, 1, 1)),
        ),
        migrations.AddField(
            model_name='judge',
            name='date_of_retirement',
            field=models.DateField(default=datetime.date(2000, 1, 1)),
        ),
        migrations.AddField(
            model_name='judge',
            name='gender',
            field=models.CharField(default='Unknown', max_length=10),
        ),
        migrations.AddField(
            model_name='judge',
            name='parent_high_court',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='judge',
            name='tenure_length',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='judge',
            name='tenure_length_as_cji',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='judge',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
